# Generated by Django 4.0.1 on 2022-02-21 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_flight_airline_name_alter_flight_flight_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='airline_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airline_name',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.PROTECT, to='flights.airline'),
        ),
    ]
